name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer/files
          key: ${{ runner.os }}-php-8.4-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-composer-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run php-cs-fixer (dry run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer/files
          key: ${{ runner.os }}-php-8.4-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run psalm
        run: vendor/bin/psalm

  tests:
    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, deps ${{ matrix.composer_args }}
    runs-on: ubuntu-latest
    needs:
      - lint
      - static-analysis
    continue-on-error: ${{ matrix.stability == 'dev' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Symfony 7.3 (stable)
          - php: '8.4'
            symfony: '7.3'
            composer_args: '--prefer-stable'
            stability: 'stable'
          - php: '8.4'
            symfony: '7.3'
            composer_args: '--prefer-lowest'
            stability: 'stable'

          # Symfony 7.4 (dev)
          - php: '8.4'
            symfony: '7.4'
            composer_args: '--prefer-stable'
            stability: 'dev'

          # Symfony 8.0 (dev)
          - php: '8.4'
            symfony: '8.0'
            composer_args: '--prefer-stable'
            stability: 'dev'

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/composer/files
          key: ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-${{ matrix.composer_args }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-${{ matrix.composer_args }}-

      - name: symfony/flex is required to install the correct symfony version
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require symfony/flex --quiet

      - name: Configure Composer stability
        run: composer config minimum-stability ${{ matrix.stability }}

      - name: Configure Symfony version for symfony/flex
        run: composer config extra.symfony.require "${{ matrix.symfony }}.*"

      - name: Install dependencies
        run: composer update ${{ matrix.composer_args }} --no-progress --no-scripts --no-plugins
      
      - name: Run phpunit
        run: vendor/bin/phpunit
