name: CI

on:
  push:
    branches: [ "1.x" ]
  pull_request:
    branches: [ "1.x" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-php-8.4-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-8.4-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run php-cs-fixer (dry run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

  tests:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        php: ['8.3', '8.4']
        symfony: ['7.4.*', '8.0.*']

    name: PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ~/.composer/cache
          key: ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-symfony-${{ matrix.symfony }}-

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Update dependencies for Symfony ${{ matrix.symfony }}
        run: |
          composer require "symfony/config:${{ matrix.symfony }}" "symfony/dependency-injection:${{ matrix.symfony }}" "symfony/doctrine-bridge:${{ matrix.symfony }}" "symfony/form:${{ matrix.symfony }}" --no-update
          composer update --prefer-dist --no-progress --optimize-autoloader

      - name: Run psalm
        run: vendor/bin/psalm

      - name: Run phpunit
        run: vendor/bin/phpunit

      - name: Check for outdated dependencies
        run: composer outdated
